### PR TITLE
Add gzip configuration on all websites

### PR DESCRIPTION
**Pull request by TimvdLippe**
I do not know where you store the configuration, but I assume it is similar to the other configuration files. Also, I pasted the gzip.conf in all `server {}` directives, not sure if that should be the case.

Anyways, I tested this locally on symposium and it reduces the total website size by ~50%

### CODE REVIEW

**Review by martijnjanssen — COMMENTED** [review]
Wouldn't a wildcard include be better like: `include /etc/nginx/sharedconfig/*.conf;` importing all files in config. By doing this, shared configs added later on will be included automatically.

**Comment by TimvdLippe** [comment]
@martijnjanssen I was not aware of that functionality, but if we can: yes sure!

**Comment by praseodym** [comment]
You need to change this; the nginx container config does something like `include config/*.conf` so it will blow up if you include a `gzip.conf` in there.

**Comment by TimvdLippe** [comment]
Done :smile:

**Comment by praseodym** [comment]
Please add the `shared` folder to `docker-compose.yml` as well :)

**Pull request merged**
